package com.example.lmsProject.security;

import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.security.Keys;
import org.junit.jupiter.api.Test;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.util.Date;

import static org.junit.jupiter.api.Assertions.*;

class SecurityAccessTest {

    @Test
    void generateToken_and_extractUsername_roundTrips() {
        String username = "alice@example.com";

        String token = JwtUtil.generateToken(username);
        assertNotNull(token, "Token should be generated by JwtUtil");

        String extracted = JwtUtil.extractUsername(token);
        assertEquals(username, extracted, "Extracted username should match the subject");

        assertTrue(JwtUtil.validateToken(token), "Token generated by JwtUtil should validate");
    }

    @Test
    void tamperedToken_isRejected() {
        String token = JwtUtil.generateToken("bob@example.com");

        // Tamper the token (breaks the signature)
        String tampered = token + "x";

        assertFalse(JwtUtil.validateToken(tampered), "Tampered token must be invalid");

        // Optional: extracting should throw
        assertThrows(JwtException.class, () -> JwtUtil.extractUsername(tampered),
                "Extracting from tampered token should fail");
    }

    @Test
    void tokenSignedWithDifferentSecret_isRejected() {
        // Create a DIFFERENT secret/key than JwtUtil's internal static KEY
        SecretKey otherKey = Keys.hmacShaKeyFor(
                "DIFFERENT-SECRET-STRING-THAN-UTIL-KEY-AT-LEAST-32-BYTES!".getBytes(StandardCharsets.UTF_8)
        );

        String username = "teacher@example.com";
        long oneMinute = 60_000L;

        // Build a token signed with the other key (valid structure, wrong signature for JwtUtil)
        String foreignToken = Jwts.builder()
                .subject(username)
                .expiration(new Date(System.currentTimeMillis() + oneMinute))
                .signWith(otherKey, SignatureAlgorithm.HS256)
                .compact();

        // JwtUtil should reject this because it verifies with its own static KEY
        assertFalse(JwtUtil.validateToken(foreignToken),
                "Token signed with a different secret must be invalid for JwtUtil");

        // Optional: extracting should throw, since signature verification fails
        assertThrows(JwtException.class, () -> JwtUtil.extractUsername(foreignToken),
                "Extracting from a token signed with a different secret should fail");
    }
}
